name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'

    - name: Build and Test
      run: mvn clean test surefire-report:report -DgenerateReports=true

    - name: Move Report to Docs
      run: |
        mkdir -p ./gh-pages
        cp -r target/site/* ./gh-pages/
        mv ./gh-pages/surefire-report.html ./gh-pages/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN_APP }}
        publish_dir: ./gh-pages
